### ISSUE TITLE
not enough kittens

### ISSUE THREAD

**Issue by InfAmelia** [sarahjschultz/kittengif#1]
can it be possible that there is too few kitten?

**Comment by sarahjschultz** [comment]
We are working on adding moar kittehs

**Comment by carlwiedemann** [comment]
We are now excited to announce a comprehensive kitten library of 300 kittens.

Somewhat related: we are also working on Android support, since these clients have had zero kittens.

Does the total 300 potentially solve this issue for the time being? We are investigating tighter Giphy integration for higher numbers in the future.

**Comment by InfAmelia** [comment]
is it possible to have 365? my use case revolves around seeing a new kitten once a day every day for a year.

**Comment by carlwiedemann** [comment]
Fixed in f6f1f772a6d54140a4f25b880bc3560534328d19

**Comment by carlwiedemann** [comment]
@InfAmelia You will be thrilled to hear that we have increased the number of kittens to 500. Enjoy.
